### ISSUE TITLE
SSL Handshake Error

### ISSUE THREAD

**Issue by keithjjones** [jheise/threatcrowd_api#1]
This caused an error:

```
>>> a = threatcrowd.ip_report('8.8.8.8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Source/Python27/lib/python2.7/site-packages/threatcrowd.py", line 14, in ip_report
    return _threatcrowd_query("ip", {"ip":address})
  File "/Source/Python27/lib/python2.7/site-packages/threatcrowd.py", line 7, in _threatcrowd_query
    data = requests.get(full_path, params=params).text
  File "/Source/Python27/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Source/Python27/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Source/Python27/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Source/Python27/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Source/Python27/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)
```

I'll try to troubleshoot, but I wanted you to know about it.

**Comment by keithjjones** [comment]
It appears to be a Mac OSX thing.  This will fix it:

```
$ pip install requests[security]
```

**Comment by jheise** [comment]
just updated requirements.txt

**Comment by jheise** [comment]
wrong project, updating setup.py now

**Comment by keithjjones** [comment]
Thanks.  Let me know if you want me to test anything.
